### ISSUE TITLE
Using queryParameters with stub registration does not work

### ISSUE THREAD

**Issue by jcbrockschmidt** [HBOCodeLabs/wiremock-captain#23]
## Expected Behavior
Registering a stub for an endpoint and encoding query parameters with the `queryParameters` request field will successfully register a stub for that endpoint + query parameter combination.

## Actual Behavior
Calls to WireMock to the registered endpoint with the associated query parameters yields a 500 response.

## Steps to Reproduce the Problem

Modify `example/express-app` as follows:

  * Add to `src/routes.ts`:
```
export async function getTestEndpointRoute(
  _request: Request,
  response: Response,
): Promise<Response> {
  const url = 'http://localhost:8080/get?testParam=foo';

  try {
    const resp = await fetch(url, {
      method: 'get',
      headers: { 'Content-Type': 'application/json' },
      timeout: 1000,
    });
    const json = await resp.json();
    return response.send(json);
  } catch (e) {
    const { name, message } = e;
    console.log(`ERROR! name=${name} message=${message}`);
    return response.sendStatus(500);
  }
}
```
  * Add to `src/app.ts` in `config()`:
```
    this.app.get('/testEndpoint', getTestEndpointRoute);
```
  * Add to `server.spec.ts` in `beforeAll()`:
```
    await mockInstance.register(
      {
        method: 'GET',
        endpoint: '/get',
        queryParameters: {
          testParam: 'foo'
        }
      },
      {
        status: 200,
        body: {
          a: 5,
        }
      }
    )
```
  * Add to `server.spec.ts` as a test:
```
  it('example test', () => {
    return supertest(serviceUrl)
      .get('/testEndpoint')
      .expect((res) => {
        expect(res.status).toEqual(200);
        expect(res.body).toEqual({
          a: 5,
        });
      });
  });
```
Then build `express-app` and run tests as outlines in the README.

Log for the test failure:
```
 FAIL  test/integration/server.spec.ts
  postProcessData
    ✓ should return 200 (40 ms)
    ✕ example test (71 ms)

  ● postProcessData › example test

    expect(received).toEqual(expected) // deep equality

    Expected: 200
    Received: 500

      57 |       .get('/testEndpoint')
      58 |       .expect((res) => {
    > 59 |         expect(res.status).toEqual(200);
         |                            ^
      60 |         expect(res.body).toEqual({
      61 |           a: 5,
      62 |         });

      at supertest.get.expect (test/integration/server.spec.ts:59:28)
      at Test.Object.<anonymous>.Test._assertFunction (node_modules/supertest/lib/test.js:285:11)
      at Test.Object.<anonymous>.Test.assert (node_modules/supertest/lib/test.js:175:21)
      at localAssert (node_modules/supertest/lib/test.js:133:12)
      at fn (node_modules/supertest/lib/test.js:130:5)
      at Test.callback (node_modules/superagent/src/node/index.js:902:3)
      at IncomingMessage.<anonymous> (node_modules/superagent/src/node/index.js:1130:18)
```

Log for the WireMock request failure:
```
Request was not matched
=======================
-----------------------------------------------------------------------------------------------------------------------
| Closest stub | Request |
-----------------------------------------------------------------------------------------------------------------------
|
GET | GET
/get | /get?testParam=foo <<<<< URL does not match
|
Query: testParam = foo | testParam: foo
|
|
-----------------------------------------------------------------------------------------------------------------------
```

If you instead register the WireMock stub like this,
```
    await mockInstance.register(
      {
        method: 'GET',
        endpoint: '/get?testParam=foo'
      },
      {
        status: 200,
        body: {
          a: 5,
        }
      }
    )
```
there are no issues.

## Specifications

- Version: 1.4.0
- Platform: macOS Catalina

**Comment by satvik-s** [comment]
Hi!

I guess you are looking for this: https://github.com/HBOCodeLabs/wiremock-captain/blob/92de1094c994b6596b18c8248ae806ad76d412e2/src/IWireMockFeatures.ts#L47

**Comment by satvik-s** [comment]
Let me know if using the above solves your problem.

If yes, we should be good to close out the issue.

**Comment by jcbrockschmidt** [comment]
> Hi!
> 
> I guess you are looking for this:
> 
> https://github.com/HBOCodeLabs/wiremock-captain/blob/92de1094c994b6596b18c8248ae806ad76d412e2/src/IWireMockFeatures.ts#L47

Yes! This worked. I successfully registered the stub like this:
```
    await mockInstance.register(
      {
        method: 'GET',
        endpoint: '/get',
        queryParameters: {
          testParam: 'foo'
        }
      },
      {
        status: 200,
        body: {
          a: 5,
        }
      },
      {
        requestEndpointFeature: EndpointFeature.UrlPath,
      }
    )
```

Thanks!
